### ISSUE TITLE
Remove StackOverflow link in the community page

### ISSUE THREAD

**Issue by Panquesito7** [julelang/website#13]
### Description

Currently, there are no Jule-related questions on StackOverflow.
We probably should remove that button and change it to something else, not sure what that could be, though.

Let me know your thoughts. Thanks. 🙂

**Comment by mertcandav** [comment]
Yeah. It was much of a future-proof addition. But I guess we can remove it for now and add back it when it's really functional. I'm not sure we should put anything in its place. For now, I don't think we have as functional an option as Discord or GittHub. We can just remove it.

**Comment by mertcandav** [comment]
The StackOverflow option removed from community links with this commit: a60dc7d

Thanks for your contribution.
