### ISSUE TITLE
Add a dark mode to the website

### ISSUE THREAD

**Issue by Panquesito7** [julelang/website#14]

**Comment by mertcandav** [comment]
Adding a dark mode to a website may require changing the design. In its current state, dark mode color tones are dominant in general. But if we are considering a redesign to add a light/dark theme option, I would agree.

@lareii What do you think about it?

**Comment by lareii** [comment]
good idea. i was already thinking about updating the site, i'll take a look at this.

**Comment by lareii** [comment]
added theme change based on system default, thanks.
