### ISSUE TITLE
Improve sample codes

### ISSUE THREAD

**Issue by Panquesito7** [julelang/website#15]
### Description

The sample codes are missing a few non-code improvements.
Here are some that could be implemented, in my opinion:

1. Fully document the sample codes and explain what each function does and everything. Doxygen can be used.
2. Add syntax coloring to make it more beautiful and understandable.
3. A few more examples could be added for more variety and a basic understanding/knowledge of the language at first glance. For example: `if else cases` would be awesome.

Let me know your thoughts. Thanks. 🙂

**Comment by mertcandav** [comment]
I've improved the existing codes a little bit, additionally added FizzBuzz and Levenshtein Distance algorithms. If you have any algorithm suggestions, please share them with us.

I think it could also be good with documentation, but without syntax highlighting, I think it would add more complexity for just the reviewers. That's why I'm in the opinion of adding the documentation with syntax highlighting. I have no clear idea if syntax highlighting is possible. @lareii What do you think about syntax highlighting?

**Comment by Panquesito7** [comment]
> I've improved the existing codes a little bit, additionally added FizzBuzz and Levenshtein Distance algorithms. If you have any algorithm suggestions, please share them with us.

Cool, thank you! Adding `if else` case examples would be great as well, it's one of the most used things, IMO.

**Comment by mertcandav** [comment]
Is there an algorithm you suggest we add for `if else` example?

**Comment by Panquesito7** [comment]
Good question, not sure about that. Probably something simple related to printing numbers, such as odd/even numbers? 🤔

**Comment by mertcandav** [comment]
I'm thinking of an example that might make a little more detailed. But if we improve the example you mentioned a little more, I think it could be something like the following:

```
enum NumberKind {
	Even,
	Odd,
	Zero,
}

fn kind_of_number(x: int): NumberKind {
	if x == 0 {
		ret NumberKind.Zero
	} else if x%2 == 0 {
		ret NumberKind.Even
	} else {
		ret NumberKind.Odd
	}
}

fn main() {
	outln(kind_of_number(10))
	outln(kind_of_number(0))
	outln(kind_of_number(1))
}
```

**Comment by lareii** [comment]
idk how to implement the highligthing but i'll do my best.

**Comment by mertcandav** [comment]
I added `Number Kind` example program, includes `enum` and `if-else` chains.
Syntax highlighting is controversial and it's not main purpose of this issue, so I'll close this issue.
