### ISSUE TITLE
Is a license page needed?

### ISSUE THREAD

**Issue by Panquesito7** [julelang/website#17]
### Description

Instead of adding a whole license page, we can add a source code section explaining that it's fully open-source and such.
But I think that should be in the future, once the language has more popularity and the website has more sections too.

For now, I suggest removing the page, as the license is already provided in each of the repositories, and the users should take a look at the given repository's license instead.
Let me know what you think. Thanks. 🙂

**Comment by mertcandav** [comment]
You seem right. Let's remove the relevant license page.

**Comment by mertcandav** [comment]
The license page removed with this commit: ee7365d

Thanks for your contribution.
