### ISSUE TITLE
Incorporate the Gitpod Ready-to-code system

### ISSUE THREAD

**Issue by Panquesito7** [julelang/website#18]
### Description

With [Gitpod.io](https://www.gitpod.io), everyone can easily compile the website's code and run it in one single click, which will make it easier for contributors to make changes, especially for those that do not have the required tools or such.
This has been added in a lot of repositories and is highly configurable. Those who opt to not use this tool can compile the website locally on their machines.

If this is accepted, I'd like to work on this. Thank you. 🙂

**Comment by mertcandav** [comment]
This is a good idea.
We look forward to your work. If you need any help, please feel free to contact us.

Thanks.

**Comment by Panquesito7** [comment]
Cool, thanks! Working on this. 🙂
