### ISSUE TITLE
Create a download page

### ISSUE THREAD

**Issue by Panquesito7** [julelang/website#24]
### Description

Currently, the link to downloads links to the releases page, which is not user-friendly.
It'd be great if we could have a download page with buttons for Unix/Windows, the source code, previous versions, etc. so that it's more accessible.

What do you think? Thanks. 🙂

**Comment by mertcandav** [comment]
I agree with that. But I guess we'll have to add the versions manually. Fortunately, there are not many releases. It won't take long to do this.

A home page listing releases and subpages with release notes for releases would be nice.

@lareii What do you think?

**Comment by lareii** [comment]
not sure for release notes but i can create a download page for latest release

**Comment by mertcandav** [comment]
Can't we just create a home page where each release is listed, and just a separate page for their release notes?

**Comment by Panquesito7** [comment]
For release notes, we should just link to the releases page of Jule, IMO.

**Comment by mertcandav** [comment]
> For release notes, we should just link to the releases page of Jule, IMO.

Actually, yes. This approach also reduces workload of release process and GitHub release notes are pretty readable already. Therefore, we can use GitHub for release notes. We just need download page.

**Comment by lareii** [comment]
yeah, we can use github. ill do it.

**Comment by lareii** [comment]
created a download page with all versions listed.
https://jule.dev/downloads
