### ISSUE TITLE
Is the CoC derived from Contributor Covenant?

### ISSUE THREAD

**Issue by Panquesito7** [julelang/website#26]
### Description

It looks like the Code of Conduct is derived from the [Contributor Covenant CoC](https://www.contributor-covenant.org/).
If so, we should give credit, attribute, and link to their page on the CoC page. This is 100% required due to [its license](https://github.com/EthicalSource/contributor_covenant/blob/release/LICENSE.md).

**Comment by mertcandav** [comment]
Yes. We did not know about the license. Thank you.
Would you like to make the relevant changes?

**Comment by Panquesito7** [comment]
Sure, I'll work on that. 🙂
