### ISSUE TITLE
Minor improvements needed on downloads page

### ISSUE THREAD

**Issue by mertcandav** [julelang/website#30]
The feature added to the download page with PR #29  has a bug. Download sections can be toggle from anywhere in the list, but the list content does not toggle even if the `+`/`-` icon changes its current state as a result of interaction.

In addition, text selection is active for `+`/`-` icon.
It might be better to disable it.

Tried on Google Chrome, Firefox, and Safari.
And just Safari has this problem.

**Comment by Panquesito7** [comment]
Microsoft Edge seems to work properly.

**Comment by mertcandav** [comment]
Website is rewritten, new version is not has this issue.

**Comment by mertcandav** [comment]
Here is the rewrite commit: 923095bfe27a3f171a34c29f00162c0f5bfa488a
