### ISSUE TITLE
Add release date for each release in the downloads page

### ISSUE THREAD

**Issue by Panquesito7** [julelang/website#34]
### Description

It'd be great and easier to know when was the given release/download released.
I do not think this is very hard to implement, I believe the API has information about the release date.

If you like the idea, I would like to work on this. 🙂

**Comment by mertcandav** [comment]
Sounds good!
Your PR will be merged.

**Comment by Panquesito7** [comment]
Sorry for the late reply. Working on it.

**Comment by lareii** [comment]
yeah, i am working on it. i'll implement it.

**Comment by mertcandav** [comment]
The new site has been published.

It includes the release time for each build. This may be enough. To make it look better, only year, month and day data can be added, and a single date for release can be shown directly instead of builds.
